# Generated by Django 4.2.2 on 2023-07-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
    ]
